/**
Components on the screen:
A text input;
An add button;
A list of todos below, with each todo having a checkbox. clicking on the checkbox would mark the todo "done" or "undone" based on its previous state. also a delete button to remove the todo item.

State:
All current todo items, with id, text, done. array of todo. id is generated by a monotonic counter.

Event listeners:
Add button: clicking on it adds the todo, and clears the text input.
Remove button: clicking on it removes the todo.
Checkbox: clicking on it flips the todo state of the item.

Lifecycle / Process:
- mount() function is called to mount the components mentioned above on the screen, attach event listeners for the input bar, add & remove buttons. notice that the event listeners for the remove button also exist during initial mount, living at the top level <ul> element instead of each <li> element.
- update(): renders the updated todo list
 */

type TodoItem = {
  id: number;
  text: string;
  done: boolean;
};

let idCounter = 0;

type State = {
  todos: TodoItem[];
};

let state: State = {
  todos: [],
};

function setState(next: Partial<State>) {
  state = { ...state, ...next };
  update();
}

const root = document.getElementById("app")!;

function mount() {
  root.innerHTML = `
  <input type="text" id="text-input">
  <button id="add-button">Add</button>
  <br>
  <ul id="todo-list"></ul>
  `;

  const addButton = document.getElementById("add-button")!;
  addButton.addEventListener("click", handleAddTodo);

  const ul = document.getElementById("todo-list")!;
  ul.addEventListener("click", handleListClick);
  ul.addEventListener("dblclick", handleListDoubleClick);
}

function handleAddTodo() {
  const textInput = document.getElementById("text-input")! as HTMLInputElement;
  const todoText = textInput.value?.trim();
  if (!todoText) {
    // Should surface a warning saying "Todo cannot be empty."
    return;
  }
  textInput.value = "";
  const newTodos = [
    ...state.todos,
    {
      id: idCounter++,
      text: todoText,
      done: false,
    },
  ];
  setState({ todos: newTodos });
}

function handleListClick(e: MouseEvent) {
  const target = e.target as HTMLElement;

  const li = target.closest("li[data-id]") as HTMLLIElement | null;
  if (!li) return;
  const id = Number(li.dataset.id);

  const action = target.dataset.action;

  if (action === "delete") {
    setState({ todos: state.todos.filter((todo) => todo.id !== id) });
  } else if (action === "toggle") {
    setState({
      todos: state.todos.map((todo) =>
        todo.id === id ? { ...todo, done: !todo.done } : todo,
      ),
    });
  } else if (action === "save") {
    const editor = li.querySelector(".todo-editor")! as HTMLInputElement;
    const newTodoText = editor.value.trim();
    if (!newTodoText) {
      // Should surface a warning saying "Todo cannot be empty."
      return;
    }
    setState({
      todos: state.todos.map((todo) =>
        todo.id === id ? { ...todo, text: newTodoText } : todo,
      ),
    });
  }
}

function handleListDoubleClick(e: MouseEvent) {
  const target = e.target as HTMLElement;
  const li = target.closest("li[data-id]") as HTMLLIElement | null;
  if (!li) return;

  const checkbox = li.querySelector(".todo-checkbox")! as HTMLInputElement;
  checkbox.disabled = true;

  const text = li.querySelector(".todo-text")! as HTMLSpanElement;
  text.hidden = true;

  const editor = li.querySelector(".todo-editor")! as HTMLInputElement;
  editor.hidden = false;
  editor.focus();
  editor.addEventListener("blur", (e) => handleCancelEdit(li, e), {
    once: true,
  });
  // editor.addEventListener("keydown", handleKeydown())

  const deleteBtn = li.querySelector(".delete-btn")! as HTMLButtonElement;
  deleteBtn.hidden = true;

  const saveBtn = li.querySelector(".save-btn")! as HTMLButtonElement;
  saveBtn.hidden = false;
}

function handleCancelEdit(li: HTMLLIElement, e: FocusEvent) {
  const secondaryTarget = e.relatedTarget as HTMLElement | null;
  const saveBtn = li.querySelector(".save-btn")! as HTMLButtonElement;
  if (secondaryTarget && secondaryTarget === saveBtn) {
    return;
  }
  const checkbox = li.querySelector(".todo-checkbox")! as HTMLInputElement;
  checkbox.disabled = false;

  const text = li.querySelector(".todo-text")! as HTMLSpanElement;
  text.hidden = false;

  const editor = li.querySelector(".todo-editor")! as HTMLInputElement;
  editor.hidden = true;

  const deleteBtn = li.querySelector(".delete-btn")! as HTMLButtonElement;
  deleteBtn.hidden = false;

  saveBtn.hidden = true;
}

function update() {
  const ul = document.getElementById("todo-list")! as HTMLUListElement;
  ul.innerHTML = state.todos
    .map((todo) => {
      return `
    <li data-id="${todo.id}">
      <input type="checkbox" ${todo.done ? "checked" : ""} data-action="toggle" class="todo-checkbox">
      <span class="todo-text">${todo.text}</span>
      <input type="text" value="${todo.text}" class="todo-editor" hidden>
      <button data-action="delete" class="delete-btn">Delete</button>
      <button data-action="save" class="save-btn" hidden>Save</button>
    </li>
    `;
    })
    .join("");
}

mount();
