/**
Components on the screen:
A text input;
An add button;
A list of todos below, with each todo having a checkbox. clicking on the checkbox would mark the todo "done" or "undone" based on its previous state. also a delete button to remove the todo item.

State:
All current todo items, with id, text, done. array of todo. id is generated by a monotonic counter.

Event listeners:
Add button: clicking on it adds the todo, and clears the text input.
Remove button: clicking on it removes the todo.
Checkbox: clicking on it flips the todo state of the item.

Lifecycle / Process:
- mount() function is called to mount the components mentioned above on the screen, attach event listeners for the input bar, add & remove buttons. notice that the event listeners for the remove button also exist during initial mount, living at the top level <ul> element instead of each <li> element.
- update(): renders the updated todo list
 */

type TodoItem = {
  id: number;
  text: string;
  done: boolean;
};

let idCounter = 0;

type State = {
  todos: TodoItem[];
};

let state: State = {
  todos: [],
};

function setState(next: Partial<State>) {
  state = { ...state, ...next };
  update();
}

const root = document.getElementById("app")!;

function mount() {
  root.innerHTML = `
  <input type="text" id="text-input">
  <button id="add-button">Add</button>
  <br>
  <ul id="todo-list"></ul>
  `;

  const addButton = document.getElementById("add-button")!;
  addButton.addEventListener("click", handleAddTodo);

  const ul = document.getElementById("todo-list")!;
  ul.addEventListener("click", handleListClick);
}

function handleAddTodo() {
  const textInput = document.getElementById("text-input")! as HTMLInputElement;
  const todoText = textInput.value?.trim();
  if (!todoText) {
    return;
  }
  textInput.value = "";
  const newTodos = [
    ...state.todos,
    {
      id: idCounter++,
      text: todoText,
      done: false,
    },
  ];
  setState({ todos: newTodos });
}

function handleListClick(e: MouseEvent) {
  const target = e.target as HTMLElement;

  const li = target.closest("li[data-id]") as HTMLLIElement | null;
  if (!li) return;
  const id = Number(li.dataset.id);

  const action = target.dataset.action;

  if (action === "delete") {
    setState({ todos: state.todos.filter((todo) => todo.id !== id) });
  } else if (action === "toggle") {
    setState({
      todos: state.todos.map((todo) =>
        todo.id === id ? { ...todo, done: !todo.done } : todo,
      ),
    });
  }
}

function update() {
  const ul = document.getElementById("todo-list")! as HTMLUListElement;
  ul.innerHTML = state.todos
    .map((todo) => {
      return `
    <li data-id="${todo.id}">
      <input type="checkbox" ${todo.done ? "checked" : ""} data-action="toggle">
      <span data-action="toggle">${todo.text}</span>
      <button data-action="delete">Delete</button>
    </li>
    `;
    })
    .join("");
}

mount();
